### GET categories
GET http://localhost:3010/api/categories HTTP/1.1

### GET categories with count
GET http://localhost:3010/api/categories?count=true HTTP/1.1

### GET aticles by category
GET http://localhost:3010/api/categories/1 HTTP/1.1

### GET parts aticles by category
GET http://localhost:3010/api/categories/1?offset=0&limit=8 HTTP/1.1
